### ISSUE TITLE
POSTs turned into GETs?

### ISSUE THREAD

**Issue by tyardley** [tes/compoxure#57]
Hi, 

I've just installed compoxure and been playing around with the example app. I may be wrong but from the tests I've done so far it seems that when I POST to the compoxure server, it passes it through to the backend server but as a GET?

I've tried digging to see if I've configured anything incorrectly, but from passthrough.js I can't see anywhere where the verb would be being set in the request which is passed on.

Does anyone else see this behaviour?

**Comment by cliftonc** [comment]
Normally it will reject a POST outright unless you configure it to allow it through, which case it should travel through unmolested.

https://github.com/tes/compoxure/blob/master/test/common/testConfig.json#L54

The 'normal' use case for Compoxure though is only serving GET's, we route anything that isn't a get directly to the backend service (we have nginx in front of Compoxure here at TES).

Can you share your config / project and we may be able to assist more.

**Comment by tyardley** [comment]
Hi, 

Thanks very much for the swift reply. I think I've managed to get to the bottom of my specific problem.

I'm running with pretty much the example setup, I've just changed the server setups to bind only on port and not localhost so I can run it in docker on Windows.

I think the main problem wasn't that the POSTs weren't getting identified to be passed through, but that when they were handled by passthrough.js they were passed on as GETs:
https://github.com/tes/compoxure/blob/master/src/middleware/passthrough.js#L36

I added a clause in passthrough.js to specifically handle POSTs:

      if (req.method === 'POST') {
           req.pipe(request.post(forwardUrl, {form:req.body})).pipe(res);
      }
      else {
           req.pipe(request(requestConfig)).pipe(res);
      }

I also reordered the checks within passthrough.js on whether to pass a request through. I believe the req.backend.passthrough value is set from the configuration and as this was the first check, and returned false if it wasn't met, you have to configure each path a form sits at manually. I moved the check on request method up so that all form posts would be passed through.

Appreciate this may just be my specific requirements, but thought I'd share in case any of it was useful, and there's also a demo form in the example which I don't think functions at the moment.

**Comment by cliftonc** [comment]
Sounds like you found and fixed a bug, are you able to submit the fix as a PR?

**Comment by tyardley** [comment]
Sure, will do

**Comment by tyardley** [comment]
Hi,

I'm having trouble running the unit tests locally, I get the 2 issues below on a fresh checkout. 

I've not spent much time digging into these yet to be honest, but before I did I just wanted to check if they were known, and if you have any guidance on getting an environment set-up? I'm guessing there's something in my set-up the tests aren't liking, I'm currently running this on an Ubuntu docker container with nginx and redis installed.

  1) Page Composer should add no-cache, no-store, must-revalidate cache-control header if any fragments use cx-no-cache:
     Uncaught Error: expected 'no-store' to equal 'no-cache, no-store, must-revalidate'
      at Assertion.assert (/var/compoxure/node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (/var/compoxure/node_modules/expect.js/index.js:216:10)
      at Function.equal (/var/compoxure/node_modules/expect.js/index.js:499:17)
      at Request._callback (/var/compoxure/test/acceptance/compoxure.test.js:128:61)
      at Request.self.callback (/var/compoxure/node_modules/request/request.js:199:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/var/compoxure/node_modules/request/request.js:1036:10)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/var/compoxure/node_modules/request/request.js:963:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:448:13)

  2) Page Composer should pass through cache-control header:
     Uncaught Error: expected 'no-store' to equal 'no-cache, no-store, must-revalidate, private, max-stale=0, post-check=0, pre-check=0'
      at Assertion.assert (/var/compoxure/node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (/var/compoxure/node_modules/expect.js/index.js:216:10)
      at Function.equal (/var/compoxure/node_modules/expect.js/index.js:499:17)
      at Request._callback (/var/compoxure/test/acceptance/compoxure.test.js:136:61)
      at Request.self.callback (/var/compoxure/node_modules/request/request.js:199:22)
      at Request.emit (events.js:98:17)
      at Request.<anonymous> (/var/compoxure/node_modules/request/request.js:1036:10)
      at Request.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/var/compoxure/node_modules/request/request.js:963:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:944:16
      at process._tickCallback (node.js:448:13)

**Comment by skhoshoo** [comment]
I just did the following:
```
git clone git@github.com:tes/compoxure.git
cd compoxure/
npm i
npm test
```
and all tests pass. Do you have reliable-get@0.1.30 installed? E.g.,
```
mac sid:~/ws/compoxure 12:46:14 $ npm ls reliable-get
compoxure@0.3.85 /Users/sid/ws/compoxure
└── reliable-get@0.1.30 
```
